/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.animales.vista;

import com.animales.controller.AnimalController;
import com.animales.model.AnimalesModel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dandres
 */
public class AnimalesVista extends javax.swing.JFrame {

    AnimalController controlador = AnimalController.getController();

    public AnimalesVista() {
        initComponents();
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guardar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        idlabel = new javax.swing.JLabel();
        razalabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombrelabel = new javax.swing.JLabel();
        edadlabel = new javax.swing.JLabel();
        generolabel = new javax.swing.JLabel();
        alimentacionlabel = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldRaza = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldEdad = new javax.swing.JTextField();
        jTextFieldGenero = new javax.swing.JTextField();
        jTextFieldAlimentacion = new javax.swing.JTextField();
        consultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardar(evt);
            }
        });

        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditar(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminar(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalir(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable);

        idlabel.setText("ID");

        razalabel.setText("RAZA");

        nombrelabel.setText("NOMBRE");

        edadlabel.setText("EDAD");

        generolabel.setText("GENERO");

        alimentacionlabel.setText("ALIMENTACION");

        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(guardar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(razalabel)
                                    .addComponent(nombrelabel)
                                    .addComponent(idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edadlabel)
                                    .addComponent(generolabel)
                                    .addComponent(alimentacionlabel))))
                        .addGap(18, 18, 18)
                        .addComponent(editar)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldAlimentacion)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldGenero, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldEdad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldRaza, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(eliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(salir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consultar)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consultar)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idlabel)
                            .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(razalabel))
                    .addComponent(jTextFieldRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrelabel)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edadlabel)
                    .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generolabel)
                    .addComponent(jTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alimentacionlabel)
                    .addComponent(jTextFieldAlimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar)
                    .addComponent(editar)
                    .addComponent(eliminar)
                    .addComponent(salir))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardar

        try {
            controlador.setAnimalActual(new AnimalesModel(Integer.parseInt(jTextFieldID.getText()), jTextFieldRaza.getText(), jTextFieldNombre.getText(),
                    Integer.parseInt(jTextFieldEdad.getText()), jTextFieldGenero.getText(), jTextFieldAlimentacion.getText()));
            if (controlador.addAnimal()) {
                JOptionPane.showMessageDialog(null, "Registro guardado exitosamente");
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Error a guardar");
            }
            controlador.recargarListaAnimales();
            actualizarTabla();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Datos mal ingresados", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_botonGuardar

    private void BotonEditar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditar

        try {
            controlador.setAnimalActual(new AnimalesModel(Integer.parseInt(jTextFieldID.getText()), jTextFieldRaza.getText(), jTextFieldNombre.getText(),
                    Integer.parseInt(jTextFieldEdad.getText()), jTextFieldGenero.getText(), jTextFieldAlimentacion.getText()));
            if (controlador.updateAnimal()) {
                JOptionPane.showMessageDialog(null, "Registro Modificado");
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Error al modificar");
            }
            controlador.recargarListaAnimales();
            actualizarTabla();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Datos mal ingresados", "ERRRO", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_BotonEditar

    private void BotonEliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminar
        try {
            int fila = jTable.getSelectedRow();
            int id = Integer.parseInt(jTable.getValueAt(fila, 0).toString());
            controlador.setId(id);

            if (controlador.deleteAnimal(id)) {
                JOptionPane.showMessageDialog(null, "registro eliminada Exitosamente");
                limpiar();
            }else{
                 JOptionPane.showMessageDialog(null, "Erro ID no existente");
            }
            controlador.recargarListaAnimales();
            actualizarTabla();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR FILA NO SELECCIONADA", "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_BotonEliminar

    private void BotonSalir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalir
   
        System.exit(0);
    }//GEN-LAST:event_BotonSalir

    private void BotonConsultar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultar
        
        int fila = jTable.getSelectedRow();
        if (fila>=0){
            jTable.getValueAt(fila, 3).toString();
            jTextFieldID.setText(jTable.getValueAt(fila, 0).toString());
            jTextFieldRaza.setText(jTable.getValueAt(fila, 1).toString());
            jTextFieldNombre.setText(jTable.getValueAt(fila, 2).toString());
            jTextFieldEdad.setText(jTable.getValueAt(fila, 3).toString());
            jTextFieldGenero.setText(jTable.getValueAt(fila, 4).toString());
            jTextFieldAlimentacion.setText(jTable.getValueAt(fila, 5).toString());
        }else{
            JOptionPane.showMessageDialog(null, "Fila no seleccionada");
        }
        
    }//GEN-LAST:event_BotonConsultar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimalesVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimalesVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimalesVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimalesVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimalesVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alimentacionlabel;
    private javax.swing.JButton consultar;
    private javax.swing.JLabel edadlabel;
    private javax.swing.JButton editar;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel generolabel;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel idlabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldAlimentacion;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldRaza;
    private javax.swing.JLabel nombrelabel;
    private javax.swing.JLabel razalabel;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables

    public void actualizarTabla() {
        String[] titulos = {"ID", "RAZA", "NOMBRE", "EDAD", "GENERO", "ALIMENTACIÓN"};

        DefaultTableModel dt = new DefaultTableModel(null, titulos);
        List<AnimalesModel> male = controlador.getListaAnimales();
        String[] fila = new String[6];

        for (AnimalesModel animal : male) {
            fila[0] = String.valueOf(animal.getIdAnimal());
            fila[1] = animal.getRaza();
            fila[2] = animal.getNombre();
            fila[3] = String.valueOf(animal.getEdad());
            fila[4] = animal.getGenero();
            fila[5] = animal.getAlimentacion();
            dt.addRow(fila);
        }
        jTable.setModel(dt);
    }

    private void limpiar() {
        jTextFieldID.setText("");
        jTextFieldRaza.setText("");
        jTextFieldNombre.setText("");
        jTextFieldEdad.setText("");
        jTextFieldGenero.setText("");
        jTextFieldAlimentacion.setText("");
    }

}
